import Footer from '../../components/footer/footer';
import styles from '../../styles/Home.module.css';
import Banner from "../../components/banner/banner";
import Navbar from '../../components/navbar/navbar';
import NewsSection from '../../components/news-section/news_section';
import NewsArticle from '../../components/news-section/news_article';

export default function News() {
    const renderNews = () => {
        const posts = [
            {
                title: "Titre 1",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            },
            {
                title: "Titre 2",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            },
            {
                title: "Titre 3",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            },
            {
                title: "Titre 4",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            },
            {
                title: "Titre 5",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            },
            {
                title: "Titre 6",
                content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consequat lacus justo, et volutpat urna ultrices dictum. Quisque euismod facilisis nunc, nec posuere erat interdum at. Duis sit amet tellus ornare, posuere lorem sit amet, tristique libero. Ut eu venenatis metus, nec accumsan urna. Vestibulum non pharetra nibh, in placerat nisl. Vivamus viverra massa eu ipsum congue, sit amet suscipit nisi feugiat. Maecenas eget mi scelerisque, volutpat orci quis, ornare augue. Sed convallis imperdiet nulla, ut ullamcorper lacus molestie vel. Duis nisl nulla, posuere at lacus et, pretium finibus enim. Vestibulum a vehicula tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam in euismod elit.\n\n Etiam pulvinar est id maximus sagittis. Quisque at porta ligula, ullamcorper lobortis ligula. Aliquam eget massa sagittis, eleifend ante vitae, imperdiet tellus. Pellentesque ornare lorem vel molestie rhoncus. Cras imperdiet, quam id blandit venenatis, ex ex ultrices elit, sit amet molestie ante nibh quis justo. Sed interdum, est sit amet lobortis pretium, tortor risus rhoncus quam, sed pulvinar eros ex commodo elit. In faucibus purus sit amet ex vulputate, ut imperdiet sapien convallis. In a condimentum purus. Nullam accumsan porttitor tortor id viverra. Nulla facilisi. Praesent tincidunt lacus ut vehicula tristique. In ut semper purus. \n\nMorbi vel varius sem, eget ullamcorper ligula. Phasellus efficitur faucibus quam, at efficitur leo euismod at. Proin pulvinar placerat sapien ut pulvinar. Nam et odio tortor. Cras vel felis vitae nunc tristique sagittis nec dignissim orci. Praesent varius tempor ipsum. Donec justo ipsum, finibus et auctor nec, ullamcorper at risus. Praesent et consequat ligula. Nulla felis velit, euismod sit amet quam sollicitudin, sodales pharetra odio. Sed venenatis, arcu eget accumsan auctor, dui lacus fermentum elit, at consectetur sem sapien ac est. Donec volutpat aliquam imperdiet. Pellentesque nec dictum odio, id tincidunt dolor. Aliquam mattis tempor augue, vel hendrerit elit condimentum nec. Donec blandit porta rutrum. Aenean et dignissim turpis. Curabitur dictum lorem mi, id lacinia augue commodo vel."
            }
        ];
        
        let i = 0;

        const toRender = posts.map((post) => {
            return (
                <NewsArticle id={i++} title={post.title} content={post.content}/>
            );
        });

        return toRender;
    }

    return (
        <div className={styles.pageContainer}>
            <div className={styles.contentWrap}>
                <Navbar />
                <Banner title="Nouvelles" />
                <NewsSection>
                    {renderNews()}
                </NewsSection>
            </div>
            <Footer currentPage={1} />
        </div>
    );
}
